### ISSUE TITLE
Error applying overlay: Invalid value used as weak map key

### ISSUE THREAD

**Issue by philsturgeon** [lornajane/openapi-overlays-js#7]
Hey @lornajane, I thought I'd kick the tyres a bit and i'm getting some errors with a more simple action. Other more complex ones are working nicely, but this string replacement is throwing errors.

```yaml
overlay: 1.0.0
info:
  title: Overlay to customise API for Protect Earth
  version: 0.0.1
actions:
  - target: '$.info.description'
    description: Provide a better introduction for our end users than this techno babble.
    update: >-
      Protect Earth's Tree Tracker API will let you see what we've been
      planting and restoring all around the UK, and help support our work by
      directly funding the trees we plant or the sites we restore.

      To get involved [contact us and ask for an access token](https://protect.earth/contact) then
      [check out the API documentation](https://protect.earth/api).

```

When I run this it gives me the following error:

```
$ node openapi-overlays-js/index.js --openapi build/api/openapi.yaml --overlay api/overlays.yaml
Error applying overlay: Invalid value used as weak map key
```
